port: 3128
socks-port: 7891
allow-lan: true
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090
secret: ""
dns:
  enable: true
  ipv6: false
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
  fallback:
    - tls://dns.google
proxies:
  - name: "dfjxtj"
    type: socks5
    server: 127.0.0.1
    port: 1080
    
proxy-groups:
      # fallback 通过指定的 URL 测试并选择可用的节点，当 1 故障不可用时自动切换到 2 以此类推
  - name: "DFJX"
    type: fallback
    proxies:
      - DIRECT
      - "dfjxtj"
    url: 'http://192.168.0.2'
    interval: 300
      
rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DFJX
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
