#!/bin/bash

echo ""
dir=`git rev-parse --show-toplevel`
cd $dir

current=`date '+%s'`

FLIST=()

IFS=
for item in `git grep ";; DEPRECATED"`; do
    echo "II: $item"
    if [[ $item =~  "DEPRECATED, " ]]; then
        echo "AA: $item"
        fn=`echo $item | awk -F ":" '{print $1}'`
        echo "FN: $fn"
        date=`echo $item | awk -F "DEPRECATED, " '{print $2}'`
        echo "DATE: $date -- $((current - date))"

        if [ $((current - date)) -gt $(( 60 * 60 * 24 * 30 )) ]; then
            FLIST+=($item)
        fi
    else
        echo "BB: $item"
    fi
done

N=${#FLIST[*]}

if [ $N -gt 0 ]; then
    echo "Some files contains deprecated contents for more than 30 days:"
    for (( i=0; i<${N}; i++ ));
    do
        echo "    [$i] -- ${FLIST[$i]}"
    done

    if [ $TERM == "dumb" ]; then
        echo ""
    else
        echo "Abort commit and fix it?"
        read ans
        case $ans in
            y)
                echo "Abort.."
                exit 1
            ;;
            *)
                echo "..."
                exit 0
            ;;
        esac
    fi
fi
