(TeX-add-style-hook "article"
 (lambda ()
    (TeX-run-style-hooks
     "geometry"
     "hyperref"
     "titletoc"
     "titlesec"
     "graphicx"
     "dvips"
     "xcolor"
     "times"
     "textcomp"
     "pxfonts"
     "listings"
     "latexsym"
     "indentfirst"
     "flafter"
     "fancybox"
     "enumerate"
     "cmap"
     "cite"
     "caption2"
     "booktabs"
     "amsmath"
     "CJKutf8"
     "amssymb"
     "soul"
     "wrapfig"
     "float"
     "longtable"
     "fontenc"
     "T1"
     "inputenc"
     "utf8"
     "latex2e"
     "art11"
     "11pt")))

