#!/bin/tcsh

if ( $#argv != 1 ) then
    echo 'USAGE : setArtCover2Folder <Absolute path to directory>'
        exit
endif


if ( -d  $argv[1] ) then
       echo "Directory : $argv[1]"
else
       echo "$argv[1] is not a directory"
       exit
endif

# Create list
find $argv[1] -iname "folder.jpg" > /tmp/queue_list.txt


foreach i("`sort /tmp/queue_list.txt`")

#       set nchar = `echo $i | awk '{print length($0)}'`
#       set nchar = `expr $nchar - 10`

       set dirn = `dirname "$i"`
#`echo $i | awk '{print substr($0,0,$nchar)}'`

       echo "Generating $dirn ..."

	convert "$i" -geometry 110x110 /tmp/tmp.jpg
	convert -composite ~/SetArtCover2Folder/bg.png /tmp/tmp.jpg -gravity East "$dirn/.folder.jpg"
	convert -composite "$dirn/.folder.jpg" ~/SetArtCover2Folder/bg_reflex.png "$dirn/.folder.jpg"
       gvfs-set-attribute "$dirn" metadata::custom-icon "file://$dirn/.folder.jpg"

end


echo "Bye!"
